### ISSUE TITLE
Can't install from prebuilt wheel

### ISSUE THREAD

**Issue by Alyx-W** [m1guelpf/yt-whisper#15]
Firstly not sure if this is a user error or a project issue but I can't find anywhere else to make a request for assistance so I figured I'd do it here.

The installation instructions don't mention a rust compiler, however, when the installation is run, it says

`      If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
`

Should I try installing a Rust compiler? It sounds a bit complicated so that hasnt been my first course of action if there is a prebuilt wheel.

**Comment by m1guelpf** [comment]
You may need [`rust`](http://rust-lang.org) installed as well, in case [tokenizers](https://pypi.org/project/tokenizers/) does not provide a pre-built wheel for your platform. If you see installation errors during the `pip install` command above, please follow the [Getting started page](https://www.rust-lang.org/learn/get-started) to install Rust development environment. Additionally, you may need to configure the `PATH` environment variable, e.g. `export PATH="$HOME/.cargo/bin:$PATH"`. If the installation fails with `No module named 'setuptools_rust'`, you need to install `setuptools_rust`, e.g. by running:

```bash
pip install setuptools-rust
```
