### ISSUE TITLE
Can I use this to transcribe a local video?

### ISSUE THREAD

**Issue by aichr** [m1guelpf/yt-whisper#19]
I don't find a command for doing this? Can we have this as an option?

**Comment by ztjhz** [comment]
You can use the whisper model directly to transcribe a local video: [https://github.com/openai/whisper](https://github.com/openai/whisper)

**Comment by aichr** [comment]
My fork which support local video files in case anyone is interested 

https://github.com/aichr/yt-whisper

**Comment by m1guelpf** [comment]
You can also use the following project for local videos (with support for vtt and srt), and optionally embed the subtitles in the video.

https://github.com/m1guelpf/auto-subtitle
